export const albumList = [
  {
    id: "1",
    artist: "Cerebro de Uva",
    title: "Los Infelices",
    slug: {
      artist: "cerebro-de-uva",
      title: "los-infelices",
    },
    year: 2013,
    cover: require("@/assets/img/albums/cerebro-de-uva/los-infelices/cover.jpg"),
    artwork: ["cover.jpg", "back.jpg", "book.jpg", "inner.jpg"],
    spotifyId: "4VAqUyGkY7chvvX0FERxAH",
    details: [
      "Grabado entre diciembre de 2012 y septiembre de 2013 en Cerebrito Recs",
      "Mezclado por Santiago Jhones / Facundo Rissotti en Cerebrito Recs",
      "Masterizado por Cristian A. Graziadei en Mastering Solis",
      "Fotografía de banda: Mariel Gomez",
      "Arte: Las Crema (Florencia Rissotti / Lucía Rongo)",
      "Matto Rios: Voz y guitarra",
      "Santiago Jhones: Bajo y coros",
      "Facundo Rissotti: Teclados, programaciones y coros",
      "Alejandro Gonzalez: Bateria y coros",
      "Marcos de Cristobal: Guitarras en temas 1,2,3,4,6,7,9.",
      "Mariano Fusaro: Didjeridoo en temas 1 y 9",
      "Gisela Kinki Orlandi: trompeta en tema 5",
      "Producido por Cerebro de Uva",
    ],
    links: {
      spotify:
        "https://open.spotify.com/artist/3klJZmx8AWjHfxSA8qmMsk?si=3zqcTuzmRNmL2XUecRjpmA",
      youTube: "https://www.youtube.com/channel/UCM3moNVQ5j8En9FpIQsw--g",
    },
  },
  {
    id: "2",
    artist: "Polvo",
    title: "Pueblo Chico Infierno Grande",
    slug: {
      artist: "polvo",
      title: "pueblo-chico-infrierno-grande",
    },
    year: 2013,
    cover: require("@/assets/img/albums/polvo/pueblo-chico-infierno-grande/cover.jpg"),
    artwork: ["cover.jpg", "back.jpg", "book.jpg", "inner.jpg"],
    spotifyId: "0OjZ66pSQWiE8eRoeBxZo8",
  },
  {
    id: "3",
    artist: "Gordo",
    title: "Gordo",
    slug: {
      artist: "gordo",
      title: "gordo",
    },
    year: 2019,
    cover: require("@/assets/img/albums/gordo/gordo/cover.jpg"),
    artwork: ["front.jpg"],
    spotifyId: "0OjZ66pSQWiE8eRoeBxZo8",
  },
  {
    id: "4",
    artist: "Mar Joppich",
    title: "Remolinos",
    slug: {
      artist: "mar-joppich",
      title: "remolinos",
    },
    year: 2020,
    cover: require("@/assets/img/albums/mar-joppich/remolinos/cover.jpg"),
    artwork: ["cover.jpg"],
    spotifyId: "7umvHyhiuitbaMmgkzLQrl",
  },
  {
    id: "5",
    artist: "Facundo Rissotti",
    title: "Paisajes",
    slug: {
      artist: "facundo-rissotti",
      title: "paisajes",
    },
    year: 2010,
    cover: require("@/assets/img/albums/facundo-rissotti/paisajes/cover.jpg"),
    artwork: ["cover.jpg", "back.jpg", "cd.jpg", "inner.jpg"],
    spotifyId: "1hukLPIwKAAnyImBsbkQoj",
  },
  {
    id: "6",
    artist: "Buquino Cabrera",
    title: "Espacial",
    slug: {
      artist: "buquino-cabrera",
      title: "espacial",
    },
    year: 2015,
    cover: require("@/assets/img/albums/buquino-cabrera/espacial/cover.jpg"),
    artwork: [
      "front.jpg",
      "01-once-dias.jpg",
      "02-mundo-infinito.jpg",
      "03-el-vapor-del-tiempo.jpg",
      "04-aunque-estemos-solos.jpg",
      "05-otra.jpg",
    ],
  },
  {
    id: "7",
    artist: "Facu Dial",
    title: "EP",
    slug: {
      artist: "facu-dial",
      title: "ep",
    },
    year: 2015,
    cover: require("@/assets/img/albums/facu-dial/ep/cover.jpg"),
    artwork: ["cover.jpg", "back.jpg", "book.jpg", "inner.jpg"],
  },
  {
    id: "8",
    artist: "Cerebro de Uva",
    title: "EP",
    slug: {
      artist: "cerebro-de-uva",
      title: "ep",
    },
    year: 2014,
    cover: require("@/assets/img/albums/cerebro-de-uva/ep/cover.jpg"),
    artwork: [
      "front.jpg",
      "back.jpg",
      "01-relatos-beodos.jpg",
      "02-vos-al-sol.jpg",
      "03-canto.jpg",
      "04-pibe-de-barrio.jpg",
      "05-va-con-la-tierra.jpg",
    ],
    spotifyId: "0ZdSXkLrRdx29PrvSnGJbE",
  },
  {
    id: "9",
    artist: "Elbio Montoya",
    title: "Somos Kollas",
    slug: {
      artist: "elbio-montoya",
      title: "somos-kollas",
    },
    year: 2015,
    cover: require("@/assets/img/albums/elbio-montoya/somos-kollas/cover.jpg"),
    artwork: ["cover.jpg", "back.jpg"],
    spotifyId: "",
  },
  {
    id: "10",
    artist: "Rootstica",
    title: "Rootstica",
    slug: {
      artist: "rootstica",
      title: "rootstica",
    },
    year: 2010,
    cover: require("@/assets/img/albums/rootstica/rootstica/cover.jpg"),
    artwork: ["front.jpg", "back.jpg"],
    spotifyId: "1m1eYHsb2ZSQZTJfO6qC3q",
  },
  {
    id: "11",
    artist: "Fran Villaveirán",
    title: "La Naturaleza y el Hombre",
    slug: {
      artist: "fran-villaveiran",
      title: "la-naturaleza-y-el-hombre",
    },
    year: 2015,
    cover: require("@/assets/img/albums/fran-villaveiran/la-naturaleza-y-el-hombre/cover.jpg"),
    artwork: ["front.jpg", "back.jpg", "cd.jpg", "inner.jpg"],
  },
  {
    id: "12",
    artist: "John Angelo Cardona",
    title: "Alas de Guitarra",
    slug: {
      artist: "john-angelo-cardona",
      title: "alas-de-guitarra",
    },
    year: 2011,
    cover: require("@/assets/img/albums/john-angelo-cardona/alas-de-guitarra/cover.jpg"),
    artwork: ["cover.jpg", "back.jpg", "john.jpg", "inner.jpg"],
  },
  {
    id: "13",
    artist: "Facundo Rissotti",
    title: "Isla Negra",
    slug: {
      artist: "facundo-rissotti",
      title: "isla-negra",
    },
    year: 2007,
    cover: require("@/assets/img/albums/facundo-rissotti/isla-negra/cover.jpg"),
    artwork: ["cover.jpg", "back.jpg", "inner.jpg"],
  },
  {
    id: "14",
    artist: "Fran Villaveirán",
    title: "A Raúl Leiva",
    slug: {
      artist: "fran-villaveiran",
      title: "a-raul-leiva",
    },
    year: 2013,
    cover: require("@/assets/img/albums/fran-villaveiran/a-raul-leiva/cover.jpg"),
    artwork: ["front.jpg", "back.jpg", "xs.jpg"],
  },
];
