export const albumList = [
  {
    id: 0,
    artist: "Cerebro de Uva",
    title: "EP",
    year: 2014,
    path: "cerebro-de-uva/ep",
  },
  {
    id: 1,
    artist: "Polvo",
    title: "Pueblo Chico Infierno Grande",
    year: 2013,
    path: "polvo/pueblo-chico-infierno-grande",
  },
  {
    id: 2,
    artist: "Gordo",
    title: "Gordo",
    year: 2019,
    path: "gordo/gordo",
  },
  {
    id: 3,
    artist: "Mar Joppich",
    title: "Remolinos",
    year: 2020,
    path: "mar-joppich/remolinos",
  },
  {
    id: 4,
    artist: "Facundo Rissotti",
    title: "Paisajes",
    year: 2010,
    path: "facundo-rissotti/paisajes",
  },
  {
    id: 5,
    artist: "Buquino Cabrera",
    title: "Espacial",
    year: 2015,
    path: "buquino-cabrera/espacial",
  },
  {
    id: 6,
    artist: "Facu Dial",
    title: "EP",
    year: 2015,
    path: "facu-dial/ep",
  },
  {
    id: 7,
    artist: "Cerebro de Uva",
    title: "Los Infelices",
    year: 2013,
    path: "cerebro-de-uva/los-infelices",
  },
  {
    id: 8,
    artist: "Elbio Montoya",
    title: "Somos Kollas",
    year: 2015,
    path: "elbio-montoya/somos-kollas",
  },
  {
    id: 9,
    artist: "Rootstica",
    title: "Rootstica",
    year: 2010,
    path: "rootstica/rootstica",
  },
  {
    id: 10,
    artist: "Fran Villaveirán",
    title: "La Naturaleza y el Hombre",
    year: 2015,
    path: "fran-villaveiran/la-naturaleza-y-el-hombre",
  },
  {
    id: 11,
    artist: "John Angelo Cardona",
    title: "Alas de Guitarra",
    year: 2011,
    path: "john-angelo-cardona/alas-de-guitarra",
  },
  {
    id: 12,
    artist: "Facundo Rissotti",
    title: "Isla Negra",
    year: 2007,
    path: "facundo-rissotti/isla-negra",
  },
  {
    id: 13,
    artist: "Fran Villaveirán",
    title: "A Raúl Leiva",
    year: 2013,
    path: "fran-villaveiran/a-raul-leiva",
  },
];
