export const albumList = [
  {
    id: 0,
    artist: "Cerebro de Uva",
    title: "Los Infelices",
    year: 2013,
    cover: require("@/assets/img/albums/cerebro-de-uva/los-infelices/cover.jpg"),
  },
  {
    id: 1,
    artist: "Polvo",
    title: "Pueblo Chico Infierno Grande",
    year: 2013,
    cover: require("@/assets/img/albums/polvo/pueblo-chico-infierno-grande/cover.jpg"),
  },
  {
    id: 2,
    artist: "Gordo",
    title: "Gordo",
    year: 2019,
    cover: require("@/assets/img/albums/gordo/gordo/cover.jpg"),
  },
  {
    id: 3,
    artist: "Mar Joppich",
    title: "Remolinos",
    year: 2020,
    cover: require("@/assets/img/albums/mar-joppich/remolinos/cover.jpg"),
  },
  {
    id: 4,
    artist: "Facundo Rissotti",
    title: "Paisajes",
    year: 2010,
    cover: require("@/assets/img/albums/facundo-rissotti/paisajes/cover.jpg"),
  },
  {
    id: 5,
    artist: "Buquino Cabrera",
    title: "Espacial",
    year: 2015,
    cover: require("@/assets/img/albums/buquino-cabrera/espacial/cover.jpg"),
  },
  {
    id: 6,
    artist: "Facu Dial",
    title: "EP",
    year: 2015,
    cover: require("@/assets/img/albums/facu-dial/ep/cover.jpg"),
  },
  {
    id: 7,
    artist: "Cerebro de Uva",
    title: "EP",
    year: 2014,
    cover: require("@/assets/img/albums/cerebro-de-uva/ep/cover.jpg"),
  },
  {
    id: 8,
    artist: "Elbio Montoya",
    title: "Somos Kollas",
    year: 2015,
    cover: require("@/assets/img/albums/elbio-montoya/somos-kollas/cover.jpg"),
  },
  {
    id: 9,
    artist: "Rootstica",
    title: "Rootstica",
    year: 2010,
    cover: require("@/assets/img/albums/rootstica/rootstica/cover.jpg"),
  },
  {
    id: 10,
    artist: "Fran Villaveirán",
    title: "La Naturaleza y el Hombre",
    year: 2015,
    cover: require("@/assets/img/albums/fran-villaveiran/la-naturaleza-y-el-hombre/cover.jpg"),
  },
  {
    id: 11,
    artist: "John Angelo Cardona",
    title: "Alas de Guitarra",
    year: 2011,
    cover: require("@/assets/img/albums/john-angelo-cardona/alas-de-guitarra/cover.jpg"),
  },
  {
    id: 12,
    artist: "Facundo Rissotti",
    title: "Isla Negra",
    year: 2007,
    cover: require("@/assets/img/albums/facundo-rissotti/isla-negra/cover.jpg"),
  },
  {
    id: 13,
    artist: "Fran Villaveirán",
    title: "A Raúl Leiva",
    year: 2013,
    cover: require("@/assets/img/albums/fran-villaveiran/a-raul-leiva/cover.jpg"),
  },
];
